exports.ADMIN_ROLE = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  PRODUCT_ADMIN: 'PRODUCT_ADMIN',
  ORDER_ADMIN: 'ORDER_ADMIN',
  CLIENT_ADMIN: 'CLIENT_ADMIN',
};

exports.PRODUCT_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  HIDDEN: 'HIDDEN',
};

exports.PURCHASED_ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
};

exports.SHIPPING_ORDER_STATUS = {
  TO_SHIPPING_COMPANY: 'TO_SHIPPING_COMPANY',
  TO_CLIENT: 'TO_CLIENT',
  DELIVERED: 'DELIVERED',
};

exports.USER_ROLE = {
  CLIENT: 'CLIENT',
  SUPPLIER: 'SUPPLIER',
};

exports.OMISE = {
  PUBLIC_KEY: 'pkey_test_5saxyz4aecm6zfdkrp5',
  SECRET_KEY: 'skey_test_5saxyz5yx17gt1fh4nu',
};
